unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest is not installed - please install before continuing'
end

Vagrant.require_version ">= 1.7"
Vagrant.configure('2') do |config|

  # Configure virtualbox to allow $ram-MB memory and symlinks
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', $config[:box_ram]]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  # Use Ubuntu LTS 16.04 x64
  config.vm.box = 'ubuntu/xenial64'

  # Set up network for HTTP/HTTPS and MySQL
  config.vm.network :forwarded_port, guest: 80, host: $config[:web_port]
  # config.vm.network :forwarded_port, guest: 443, host: $config[:web_ssl_port]

  if $config[:db_service] != '' # If database is set.
    config.vm.network :forwarded_port, guest: 3306, host: 3306
  end
  if $config[:mailcatcher] # If MailCatcher is requested.
    config.vm.network :forwarded_port, guest: 1080, host: 1080
  end
  if $config[:memcache] # If Memcache will be installed.
    config.vm.network :forwarded_port, guest: 11211, host: 11211
  end

  # Sync the vagrant folder
  config.vm.synced_folder '.', '/vagrant', owner: 'www-data', group: 'www-data', :mount_options => ['dmode=777,fmode=777']

  # Use the provision script
  config.vm.provision :shell do |shell|

    # Set a name for your vm
    shell.args = "'vagrant-dev'"
    shell.path = 'vagrant/provision.sh'
    shell.env = $config

  end

end
