# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant/config'
include VConfig

Vagrant.configure('2') do |config|

  # Configure virtualbox to allow $ram-MB memory and symlinks
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', $config[:ram]]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  # Use Ubuntu LTS 14.04 x64
  config.vm.box = 'trusty64'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  # Set up network for HTTP/HTTPS and MySQL
  config.vm.network :forwarded_port, guest: 80, host: $config[:port]
  config.vm.network :forwarded_port, guest: 443, host: 8443

  if $config[:database] != '' # If database is set.
    config.vm.network :forwarded_port, guest: 3306, host: 3306
  end
  if $config[:mailcatcher] # If MailCatcher is requested.
    config.vm.network :forwarded_port, guest: 1080, host: 1080
  end
  if $config[:memcache] # If Memcache will be installed.
    config.vm.network :forwarded_port, guest: 11211, host: 11211
  end

  config.vm.network :private_network, ip: '192.168.111.222'

  config.vm.synced_folder '.', '/vagrant', owner: 'www-data', group: 'www-data', :mount_options => ['dmode=777,fmode=777']

  # Load up all the ansible
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'vagrant/ansible/playbook.yml'
    ansible.inventory_path = 'vagrant/ansible/me'
    ansible.limit = 'all'

    # Pass the variables through!
    ansible.extra_vars = $config
  end
end